# Default Configuration for MyJobSpy Analyst

# Ollama Settings
ollama:
  base_url: "http://localhost:11434" # Can be overridden by OLLAMA_BASE_URL env var
  model: "llama3:instruct"          # Can be overridden by OLLAMA_MODEL env var
  request_timeout: 450             # Timeout in seconds for requests
  max_retries: 2                   # Number of retries on failure
  retry_delay: 5                   # Base delay (seconds) for exponential backoff
  # Approx max chars for combined prompt data (resume + job). Tune based on model/memory.
  max_prompt_chars: 24000

# Prompt File Locations (relative to project root)
prompts:
  directory: "analysis/prompts"
  resume_extraction_file: "resume_extraction.prompt"
  suitability_analysis_file: "suitability_analysis.prompt" # Make sure this matches your actual filename

# JobSpy Scraping Defaults
scraping:
